version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=datab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5500:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/localtime:/etc/localtime
  server1:
    build: .  
    ports:
      - 6000:6000
    environment:
      SERVER_ID: 1
      PYTHONUNBUFFERED: 1
      POSTGRES_HOST: db
      POSTGRES_DB: datab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    depends_on: 
      - db
  server2:
    build: .
    ports:
      - 7000:6000
    environment:
      SERVER_ID: 2
      PYTHONUNBUFFERED: 1
      POSTGRES_HOST: db
      POSTGRES_DB: datab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    depends_on: 
      - db